import Au from "../zkss-au/js/globals.mjs";
import assert from 'assert';




describe('init', function() {
	
	it('Random ID', function() {
		let id1 = Au.getRandomString(50);
		let id2 = Au.getRandomString(25);
		let id3 = Au.getRandomString(50);
		assert.equal(id1.length,50);
		assert.equal(id2.length,25);
		assert.notEqual(id1,id3);//in theory this could fail if the RNG is bad enough. 
		//_ is a reserved character for appending suffixes, cannot be generated by this function
		assert.equal(id1.indexOf("_"),-1);
		assert.equal(id2.indexOf("_"),-1);
		assert.equal(id3.indexOf("_"),-1);
	});
	
	
});